fix narrowing unsigned int to bits32 errors
The bits32 datatype needs to be unsigned, or the compiler chokes like:
uni_fromuni.cc:554:16: error: narrowing conversion of '4026531840' from 'unsigned int' to 'bits32' {aka 'long int'} inside { } [-Wnarrowing]
     0xF0000000 };

Also, the bits32 datatype needs to be 'int', as 'long' might be 64bit.